# Generated by Django 3.0.7 on 2020-06-30 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('has_expiration_date', models.BooleanField(default=False)),
                ('has_series', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostPassport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=255)),
                ('document_series', models.CharField(max_length=255)),
                ('document_number', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('theft_date', models.DateField(blank=True)),
                ('insert_date', models.DateField(blank=True)),
                ('ovd', models.CharField(max_length=255)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DocumentType')),
            ],
        ),
    ]
